/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nodefriends;

import java.awt.Button;
import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.UnknownHostException;
import java.text.NumberFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.text.NumberFormatter;
import views.JFormattedTextFieldHint;
import views.JPasswordFieldHint;
import views.JTextFieldHint;

/**
 *
 * @author Admin
 */
public class Menu extends javax.swing.JFrame {
    private JTextFieldHint txtEmail = new JTextFieldHint();
    private JPasswordFieldHint txtPassword = new JPasswordFieldHint();
    private JFormattedTextFieldHint numLevel;
    private JComboBox maxFriends;
    /**
     * Creates new form LoginFacebook
     */
    public Menu() {
        initComponents();
        
        getContentPane().setBackground(new Color(255,255,255));
        jPanelCredentials.setBackground(new Color(255,255,255));
        jPanelElements.setBackground(new Color(255,255,255));
        jPanelCredentials.setFocusable(true);

        //Campo correo
        txtEmail.setHint("Email");
        txtEmail.setBounds(0, 0, 200, 40);

        //Campo contraseña
        txtPassword.setBounds(0, 40, 200, 40);
        txtPassword.setEchoChar('*');
        
        //Campo nivel
        NumberFormat format = NumberFormat.getInstance();
        NumberFormatter formatter = new NumberFormatter(format);
        formatter.setValueClass(Integer.class);
        formatter.setMinimum(1);
        formatter.setMaximum(100);
        // If you want the value to be committed on each keystroke instead of focus lost
        //formatter.setCommitsOnValidEdit(true);
        numLevel = new JFormattedTextFieldHint(formatter);
        numLevel.setHint("Level");
        numLevel.setBounds(0, 80, 200, 40);
        
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement("Numero maximo de amigos");
        model.addElement(String.valueOf(0));
        for(int x=24;x<10000;x+=36){
            model.addElement(String.valueOf(x));
        }
	maxFriends = new JComboBox( model );
        maxFriends.setBounds(0, 120, 200, 40);
        
        jPanelCredentials.add(txtEmail);
        jPanelCredentials.add(txtPassword);
        jPanelCredentials.add(numLevel);
        jPanelCredentials.add(maxFriends);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanelElements = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelCredentials = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        lblinfo = new javax.swing.JLabel();
        lblinfo1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NodeFriends V0.2");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanelElements.setPreferredSize(new java.awt.Dimension(473, 427));

        jLabel1.setIcon(new ImageIcon(new ImageIcon(this.getClass().getClassLoader().getResource("images/Logo.jpeg")).getImage().getScaledInstance(150, 40, Image.SCALE_DEFAULT)));
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout jPanelCredentialsLayout = new javax.swing.GroupLayout(jPanelCredentials);
        jPanelCredentials.setLayout(jPanelCredentialsLayout);
        jPanelCredentialsLayout.setHorizontalGroup(
            jPanelCredentialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        jPanelCredentialsLayout.setVerticalGroup(
            jPanelCredentialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        jButton1.setText("Obtener Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblStatus.setPreferredSize(new java.awt.Dimension(48, 64));

        lblinfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblinfo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelElementsLayout = new javax.swing.GroupLayout(jPanelElements);
        jPanelElements.setLayout(jPanelElementsLayout);
        jPanelElementsLayout.setHorizontalGroup(
            jPanelElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelElementsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelElementsLayout.createSequentialGroup()
                            .addComponent(lblinfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelElementsLayout.createSequentialGroup()
                            .addComponent(lblinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelElementsLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(141, 141, 141)))
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelElementsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelCredentials, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelElementsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        jPanelElementsLayout.setVerticalGroup(
            jPanelElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelElementsLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCredentials, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelElementsLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(37, 37, 37)
                        .addComponent(lblinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblinfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setAutoscrolls(true);
        jMenuBar1.setFocusable(false);

        jMenu1.setText("Archivo");

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acerca");
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Uso");
        jMenu3.setToolTipText("");
        jMenu3.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu3MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelElements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelElements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.lblinfo.setText("");//Clear status information
        
        if(!isInternetReachable()){
            this.lblinfo.setText("Revisa tu conección a internet");
            return;
        }
        
        if( txtEmail.getText().equals("Email")){
            this.lblinfo.setText("Debes escribir tu correo");
            return;
        }
        
        if(txtPassword.getText().length()<=0){
            this.lblinfo.setText("Debes escribir tu contraseña");
            return;
        }
         
        if(!numLevel.getText().matches("[0-9]+")){
            this.lblinfo.setText("El campo nivel solo acepta numeros");
            return;
        }
        
        if(Integer.parseInt(numLevel.getText())<=0){
            this.lblinfo.setText("El campo nivel solo acepta numeros positivos");
            return;
        }
       
        if(maxFriends.getSelectedIndex()==0){
            this.lblinfo.setText("Seleccionar el numero maximo de amigos a obtener");
            return;
        }
        
            this.lblStatus.setIcon(new ImageIcon(new ImageIcon(this.getClass().getClassLoader().getResource("images/loading.gif")).getImage().getScaledInstance(48, 64, Image.SCALE_DEFAULT)));
            
            this.jButton1.setEnabled(false);
            Thread thread = new Thread(){
            public void run(){
                 NodeFriends facebookNodes = new NodeFriends(txtEmail.getText(), txtPassword.getText(), Integer.parseInt(numLevel.getText()), Integer.parseInt(maxFriends.getSelectedItem().toString()));
                 int result = facebookNodes.run();

                 if(result==1){
                     Menu.lblinfo.setText("Datos obtenidos correctamente");
                 }else if(result==-1){
                     Menu.lblinfo.setText("Usuario o contraseña incorrecta");
                 }else{
                     Menu.lblinfo.setText("Ocurrio un error inesperado, vuelva a intentarlo");
                 }

                 Menu.lblStatus.setIcon(null);
                 Menu.jButton1.setEnabled(true);
                }
            };
            thread.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
        JOptionPane.showMessageDialog(null, "NodeFriends Versión 0.2\nDesarrollado por: José Luis Velázquez García\nCorreo:joseluisvzg@gmail.com");

    }//GEN-LAST:event_jMenu2MenuSelected

    private void jMenu3MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu3MenuSelected
        JOptionPane.showMessageDialog(null, "*Ingresar las credenciales de una cuenta Facebook (Primeros dos campos).\n*Ingresar el nivel de exploración(Tercer campo).\n    Ej. 1->Amigos\n          2->Amigos de amigos\n          3->Amigos de los amigos de los amigos\n          ...\n*Ingresar el numero maximo de amigos a obtener por nodo (esto a partir del nivel 2). 0 significa todos.");
    }//GEN-LAST:event_jMenu3MenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
    public static boolean isInternetReachable()
        {
            try {
                //make a URL to a known source
                URL url = new URL("http://www.google.com");
                //open a connection to that source
                HttpURLConnection urlConnect = (HttpURLConnection)url.openConnection();
                urlConnect.setConnectTimeout(5000);
                //trying to retrieve data from the source. If there
                //is no connection, this line will fail
                Object objData = urlConnect.getContent();

            } catch (UnknownHostException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
                return false;
            }
            catch (IOException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
                return false;
            }
            return true;
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanelCredentials;
    private javax.swing.JPanel jPanelElements;
    public static javax.swing.JLabel lblStatus;
    public static javax.swing.JLabel lblinfo;
    public static javax.swing.JLabel lblinfo1;
    // End of variables declaration//GEN-END:variables
}
